- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: Motion
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/button/button.yaml'
            - entity: binary_sensor.carport_motion
              tap_action: more-info
              hold_action: more-info
              show_last_changed: true
          - !include
            - '../../../base/templates/button/button.yaml'
            - entity: binary_sensor.devant_motion
              tap_action: more-info
              hold_action: more-info
              show_last_changed: true
          - !include
            - '../../../base/templates/button/button.yaml'
            - entity: binary_sensor.jardin_motion
              tap_action: more-info
              hold_action: more-info
              show_last_changed: true
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/button/button.yaml'
            - entity: binary_sensor.detecteur_hall_de_nuit_motion
              tap_action: more-info
              hold_action: more-info
              show_last_changed: true
          - !include
            - '../../../base/templates/button/button.yaml'
            - entity: binary_sensor.motion_bijkeuken
              tap_action: more-info
              hold_action: more-info
              show_last_changed: true
          - !include
            - '../../../base/templates/button/button.yaml'
            - entity: binary_sensor.motion_toilet
              tap_action: more-info
              hold_action: more-info
              show_last_changed: true