- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: "Consommation totale d'électricité"
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.energy_usage_today
              name: Aujourd'hui
              line_color: '"#0062ff"'
              graph_type: line
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.energy_cost_today
              name: Prix
              line_color: '"#ddff00"'
              graph_type: line
              decimals: 3
              font_size: 65

- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: Lectures actuelles des compteurs
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.total_day_electricity_rect
              name: Tarif de jour 
              line_color: '"#fc0303"'
              graph_type: line
              show_extrema: true
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.total_night_electricity_rect
              name: Tarif de nuit
              line_color: '"#24fc03"'
              graph_type: line
              show_extrema: true
              decimals: 3
              font_size: 65

- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: "Consommation totale de gaz"
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.gas_usage_today
              name: Aujourd'hui
              line_color: '"#9000ff"'
              graph_type: line
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.gas_cost_today
              name: Prix
              line_color: '"#ff7300"'
              graph_type: line
              decimals: 3
              font_size: 65
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.total_gas_rect
              name: Compteur
              decimals: 3
              font_size: 65


- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: "Consommation totale d'eau"
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.water_usage_today
              name: Aujourd'hui
              line_color: '"#9000ff"'
              graph_type: line
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.water_cost_today
              name: Prix
              line_color: '"#ff7300"'
              graph_type: line
              decimals: 3
              font_size: 65
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.total_water_rect
              name: Compteur
              decimals: 3
              font_size: 65