- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: 'Total Usage Electricity'
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.energy_usage_today
              name: Vandaag
              line_color: '"#0062ff"'
              graph_type: line
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.energy_cost_today
              name: Deze Maand
              line_color: '"#ddff00"'
              graph_type: line
              decimals: 3
              font_size: 65

- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: Total Usage Gas
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.gas_usage_today
              name: Today
              line_color: '"#9000ff"'
              graph_type: line
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.gas_cost_today
              name: This Month
              line_color: '"#ff7300"'
              graph_type: line
              decimals: 3
              font_size: 65

- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../base/templates/other/title-text.yaml'
        - name: Current Meter Readings
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.electricity_meter_feed_in_tariff_1
              name: Low Tariff
              line_color: '"#fc0303"'
              graph_type: line
              show_extrema: true
              decimals: 3
              font_size: 65
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.electricity_meter_feed_in_tariff_2
              name: High Tariff
              line_color: '"#24fc03"'
              graph_type: line
              show_extrema: true
              decimals: 3
              font_size: 65
      - type: horizontal-stack
        cards:
          - !include
            - '../../../base/templates/other/mini-graph.yaml'
            - entity: sensor.average_gas_usage
              name: Gas
              line_color: '"#ee00ff"'
              graph_type: line
              show_extrema: true
              decimals: 3
              font_size: 65 

