Home Assistant:
  ### Theme Home Assistant Default for Homekit Infused

  ## User Settings

  ### Background image (can be an image or a color)
  background-image: '#FFFFFF' 
  primary-background-color: 'var(--background-image)'

  ### Header Title and Subtitle/Notifications
  header-text-color: 'White'
  header-font-size: 15px
  header-font-weight: normal
  header-shadow: 0px 14px 21px -15px rgba(0,0,0,0.75)

  subtitle-text-color: 'White'
  subtitle-font-size: 12px
  subtitle-font-weight: normal

  ### Title Text Addon
  title-text-color: 'Black'
  title-text-font-size: 12px
  title-text-font-weight: bolder

  ### Display a gap at the left and right side of cards on a smartphone
  display-gap: 10px

  ### Border Radius and Box Shadow
  border-radius: 12px
  box-shadow: var(--ha-card-box-shadow, 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12) )
  bar-card-border-radius: 12px

  ### Button Colors
  button-color: '#FFFFFF'
  
  button-on-color: '#FFFFFF'
  button-on-name-color: black
  button-on-state-color: black
  button-on-label-color: gray
  button-on-lock-color: gray
  button-on-icon-color: var(--paper-item-icon-active-color)
  button-on-opacity: 1.0
  button-on-box-shadow: none

  ### Fonts
  font-family: Roboto

  name-font-size: 12px
  name-font-weight: bold

  label-font-size: 10px
  label-font-weight: normal

  state-font-size: 10px
  state-font-weight: bold

  ### Badges
  badge-font-size: 10px
  badge-font-weight: normal
  badge-text-transform: capitalize
  

  #######################################################################################################################################################
  ## Main Home Assistant Colors (ANYTHING YOU CHANGE PAST THIS LINE, IS AT YOUR OWN RISK!)

  # Card Mod
  card-mod-theme: Home Assistant
  card-mod-root-yaml: |
    .: |
      ha-menu-button {
        display: none !important;
      }
      @media (orientation: portrait) {
        paper-icon-button[icon="paper-tabs:chevron-right"] {
          display: none;
        }
        paper-icon-button[icon="paper-tabs:chevron-left"] {
          display: none;
        }
      }
      mwc-icon-button[slot="trigger"] > ha-svg-icon {
        display: none;
      }
      mwc-icon-button[slot="trigger"]::after {
        font-size: 18px;
        height: 20px; 
        width: 150px;
        margin-left: 0px;
        margin-right: 12px;
        content: "{{ user }}";
        position: absolute;
        top: 14px;
        right: 0px;
        color: var(--header-text-color);
        transform: rotateY(180deg) !important;
      }
      app-header {
        top: auto !important;
        border-top: 3px solid var(--primary-color);
        bottom: -2px !important;
        transform: unset !important;
        box-shadow: 0px -10px 21px -15px rgba(0,0,0,0.75);
      }
      app-toolbar {
        transform: rotateY(180deg) !important;
      }
      #view {
        margin-top: -59px !important;
      }
      ha-icon {
        transform: rotateY(180deg) !important;
        color: var(--header-text-color) !important;
      }

  # Primary Color
  primary-color: '#03a9f4'
  ha-card-background: 'var(--button-color)'
  paper-card-background-color: 'var(--ha-card-background)'
  paper-toast-background-color: '#821414'

  # Weather
#  weather-icon-clear-night: url("/www/images/weather-icons/clear-night.svg")
#  weather-icon-cloudy: url("/www/images/weather-icons/cloudy.svg")
#  weather-icon-fog: url("/www/images/weather-icons/fog.svg")
#  weather-icon-lightning: url("/www/images/weather-icons/lightning.svg")
#  weather-icon-lightning-rainy: url("/www/images/weather-icons/lightning.svg")
#  weather-icon-partlycloudy: url("/www/images/weather-icons/partlycloudy.svg")
#  weather-icon-pouring: url("/www/images/weather-icons/pouring.svg")
#  weather-icon-rainy: url("/www/images/weather-icons/rainy.svg")
#  weather-icon-hail: url("/www/images/weather-icons/hail.svg")
#  weather-icon-snowy: url("/www/images/weather-icons/snowy.svg")
#  weather-icon-snowy-rainy: url("/www/images/weather-icons/hail.svg")
#  weather-icon-sunny: url("/www/images/weather-icons/sunny.svg")
#  weather-icon-windy: url("/www/images/weather-icons/cloudy.svg")
#  weather-icon-windy-variant: url("/www/images/weather-icons/partlycloudy.svg")
#  weather-icon-exceptional: url("/www/images/weather-icons/exceptional.svg")