---
# FR: Envoie une notification si une MAJ de HA core est disponible
# EN: Notification if Home Assistant update available
#
# https://www.home-assistant.io/integrations/version/
#
- alias: "Alerte pour une mise à jour disponible"
  description: "Envoie une notification lorsque une nouvelle version de HA core est disponible."
  id: 8387f376-a3ca-4ec1-8838-ebb7bd5a3f8b
  trigger:
    - platform: state
      entity_id: sensor.latest_version
    - platform: homeassistant
      event: start
  condition:
    - "{{ states('sensor.latest_version') != states('sensor.version_current') }}"
    - "{{ states('sensor.version_current') != 'unknown' }}"

  action:
    - service: notify.telegram_jean
      data:
        message: >
          Une mise à jour de Home Assistant est disponible:  {{ states('sensor.latest_version') }}
    - service: persistent_notification.create
      data:
        title: Mise à jour disponible !
        message: >-
          Une mise à jour de Home Assistant est disponible !
          La version {{ states('sensor.latest_version') }} vient d'être déployée !
        notification_id: hassio_upgrade