# Homekit Infused Device Counters

# Fill this file to have the badges and device counters work in HKI.
# You can use these sensors in your badges.


# All Radiator Valves or Climate entities (ONLY climate entities can be used here!, if you have a single thermostat put it here as well)
all_climate_entities:
  entities:
    - climate.thermostat

# All Fans (Enter all your fans in here)
all_fan_entities:
  entities:

# Window Sensors
all_window_sensor_entities:
  entities:

# Door Sensors
all_door_sensor_entities:
  entities:

# Motion Sensors
all_motion_sensor_entities:
  entities:
    # - binary_sensor.carport_motion
    # - binary_sensor.devant_motion
    # - binary_sensor.jardin_motion
    # - binary_sensor.meteo_motion
    - binary_sensor.detecteur_hall_de_nuit_motion

# All Detectors (smoke/gas/fire etc)
all_detector_entities:
  entities:
   

# All Binary Sensors (put all your binary sensors here e.g. smoke/gas/fire/door/window/motion etc. You can use this as a counter on the security button)
all_binary_sensor_entities:
  entities:
    - binary_sensor.detecteur_hall_de_nuit_motion
    
# All Lights
all_light_entities:
  entities:
    - light.lampe_de_chevet
    - light.lampe_de_chevet_2
    - light.lampe_sur_pied
    - light.plafonnier
    - light.plafonnier_2
    - light.plafonnier_3

# All Devices
all_device_switch_entities:
  entities:
    - switch.shelly1_8caab5061c39
    
# All Covers
all_cover_entities:
  entities:

# All Garage Doors
all_garage_door_entities:
  entities:
