# This is the notifications page, you can edit notifications that are
# shown on the frontend in this file. This works with conditional cards.
# What this means is that the conditions need to be be met before these
# cards are shown. When there are more entities/states in a conditional
# card it will always be an 'AND' condition, it will never be an 'OR'
# condition. Edit the conditions, entities and notification content to
# your own likings.

#### #### #### #### #### #### #### #### #### #### #### #### #### #### #

# Card Config

# Example Config (You can uncomment this and edit it to your likings, if you want multiple notifications you can simply continue writing a new card below)

#- type: conditional
#  conditions:
#    - entity: binary_sensor.smoke_sensor
#      state: "off"
#    - entity: binary_sensor.front_door
#      state: "off"
#    - entity: vacuum.xiaomi_vacuum_cleaner
#      state: "docked"
#    - entity: binary_sensor.bedroom_door
#      state: "off"
#    - entity: sensor.dishwasher_status
#      state_not: "Clean"
#  card:
#    !include
#    - '../base/templates/header/notification-template.yaml'
#    - icon: mdi:check-box-outline
#      name: All clear, there are no notifications.

#- type: conditional
#  conditions:
#    - entity: binary_sensor.smoke_sensor
#      state: "on"
#  card:
#    !include
#    - '../base/templates/header/notification-template.yaml'
#    - icon: mdi:check-box-outline
#      name: Smoke detected in the Kitchen!

# - type: conditional
#   conditions:
#     - entity: input_boolean.dummy1
#       state_not: "dummy"
#   card:
#     !include
#     - '../base/templates/header/notification-template.yaml'
#     - icon: mdi:alert
#       name: Insert Notification, please open user/notifications.yaml

# Home Assistant Update
- type: conditional
  conditions:
    - entity: sensor.version_updater
      state: "Update available"
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - icon: mdi:home-assistant
      name: Il y a une mise à jour pour Home Assistant!!

# Wedding Day (number of years married)
- type: conditional
  conditions:
    - entity: sensor.anniversary_notre_mariage
      state: '0'
    - entity: alarm_control_panel.home_alarm
      state: disarmed
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - icon: mdi:ring
      name: "[[[ return `Aujourd'hui, nous sommes mariés depuis ${states['sensor.anniversary_notre_mariage'].attributes.years} ans!` ]]]"
      spin: true
# Anniversary (number of years since we are together)
- type: conditional
  conditions:
    - entity: sensor.anniversary_nous_deux
      state: '0'
    - entity: alarm_control_panel.home_alarm
      state: disarmed
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - icon: mdi:ring
      name: "[[[ return `Aujourd'hui, nous sommes ensemble depuis ${states['sensor.anniversary_nous_deux'].attributes.years} ans!` ]]]"
      spin: true
# Adaline Coquerelle
- type: conditional
  conditions:
    - entity: sensor.anniversary_anniversaire_dadaline
      state: '0'
    - entity: alarm_control_panel.home_alarm
      state: disarmed      
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - entity: input_boolean.notification_birthday
      icon: mdi:gift
      name: "[[[ return `Adaline à ${states['sensor.anniversary_anniversaire_dadaline'].attributes.years} aujourd'hui!` ]]]"
# Magalie Legrain
- type: conditional
  conditions:
    - entity: sensor.anniversary_anniversaire_de_magalie
      state: '0'
    - entity: alarm_control_panel.home_alarm
      state: disarmed      
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - entity: input_boolean.notification_birthday
      icon: mdi:gift
      name: "[[[ return `Magalie à ${states['sensor.anniversary_anniversaire_de_magalie'].attributes.years} aujourd'hui!` ]]]"
# Jean-François Coquerelle
- type: conditional
  conditions:
    - entity: sensor.anniversary_anniversaire_de_jean
      state: '0'
    - entity: alarm_control_panel.home_alarm
      state: disarmed      
  card:
    !include
    - '../base/templates/header/notification-template.yaml'
    - entity: input_boolean.notification_birthday
      icon: mdi:gift
      name: "[[[ return `Jean-François à ${states['sensor.anniversary_anniversaire_de_jean'].attributes.years} aujourd'hui!` ]]]"