- id: '1612730169588'
  alias: Allumer la lampe sur pied au couché du soleil
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 5b61cb51b3d0d46ebb60dfdd5d5d104f
    entity_id: light.lampe_sur_pied
    domain: light
    brightness_pct: 50
  mode: single
