# Customize sample file, you MUST create your own!

# To create customized entities, enter the entity you want to edit as follows, by setting
# a customization for an entity it will persist everywhere in Home Assistant and not just in lovelace.
# Do AT LEAST the basic steps as in the example below.

# light.bedroom:
#   icon: mdi:lamp
#   friendly_name: Bedroom Lamp

# Advanced Section
# HKI 3.x addons use custom attributes to filter out what should go where. If you do not plan to use addons you can skip this section.
# Currently there are three custom attributes that you can use. You can use `type:`, `room:` and `lock`. If you do not
# plan to use any of the HKI auto filling addons you can skip the next part.

# You MUST have the `room` and `type` attribute set up for each device you want to expose to HKI. `lock` is not a requirement, however
# if you want to lock a button you can try to put the following attribute `lock: true` (note that this only work on buttons)

# You can name the room any name you want as long as they correspond to what you have
# setup in the global settings. Note that the room is lowercase!! You can also specify
# a floor in the same way. Example below:

# light.bedroom:
#   icon: mdi:lamp
#   friendly_name: Bedroom Lamp
#   room: bedroom

# The `type` attribute is the other required attribute and has a few options to it, see example:

# light.bedroom:
#   icon: mdi:lamp
#   friendly_name: Bedroom Lamp
#   room: bedroom
#   type: light-standard

# You can see a list of all the available options below, please add them to all the corresponding
# entities. HKI will figure out where to put your entities based on what you fill inside this file!

# light-standard                     (use this for a normal light with only dimming or no dimming capabilities)
# light-rgb                          (use this for rgb lights)
# light-color-temp                   (use this for color temperature lights)
# switch                             (use this for devices you want to show on the devices view, ANY device you give this attribute will show up on that view and doesn't have to be a switch!)
# xbox                               (use this if you have an xbox, it will be exposed on the devices view)
# playstation                        (use this if you have a playstation)
# thermostat                         (use this for thermostats only!!!)
# non-climate-fan                    (use this for fans like exhaust fans or kitchen hoods, these will only be exposed on the devices view)
# temperature                        (use this for temperature sensors)
# humidity                           (use this for humidity sensors)
# pressure                           (use this for air pressure sensors)
# door                               (use this for door sensors)
# window                             (use this for window sensors)
# camera                             (use this for camera's)
# motion                             (use this for motion sensors)
# smoke                              (use this for smoke sensors)
# gas                                (use this for gas sensors)
# media-player                       (use this for media players)
# scene                              (use this for scenes)

# Any entity that does not have both room and type will not be found by HKI's autofill, but can ofcourse still be exposed manually by using cards in the user_content of the view.
# LIGHT
light.lampe_sur_pied:
  icon: mdi:floor-lamp
  friendly_name: Lampe sur pied
  room: Salon
  type: light-rgb

light.lampe_de_chevet:
  icon: mdi:floor
  friendly_name: Lampe de chevet
  room: Chambre
  type: light-rgb

# WASTE
sensor.recycleapp_pmd:
  friendly_name: PMC
  entity_picture: /local/images/afvalbeheer/afval_pmd_small.png

sensor.recycleapp_papier:
  friendly_name: Papier & Carton
  entity_picture: /local/images/afvalbeheer/afval_papier_small.png

sensor.recycleapp_restafval:
  friendly_name: Ordures ménagères
  entity_picture: /local/images/afvalbeheer/afval_rest_small.png

# CLIMATE
climate.thermostat: 
  icon: mdi:thermostat
  friendly_name: Boxx
  type: thermostat
  room: Salon

# SENSORS
## TEMPERATURE

sensor.temperature:
  friendly_name: Boxx
  icon: mdi:thermometer
  device_class: temperature
  type: temperature
  room: Salon

sensor.indoor_temperature:
  friendly_name: Chambre d'Adaline
  icon: mdi:thermometer
  device_class: temperature
  type: temperature
  room: chambre d'Adaline

sensor.outdoor_temperature:
  friendly_name: Extérieur
  icon: mdi:thermometer
  device_class: temperature
  type: temperature
  room: extérieur

## Humidity
sensor.humidity:
  friendly_name: Extérieur
  icon: mdi:water-percent
  type: humidity
  room: extérieur

sensor.indoor_humidity:
  friendly_name: Chambre d'Adaline
  icon: mdi:water-percent
  type: humidity
  room: chambre d'Adaline

## Air Pressure
sensor.relative_pressure:
  friendly_name: Extérieur
  icon: mdi:gauge
  # icon: mdi:water-percent
  type: pressure
  room: extérieur

# Battery Sensors
sensor.iphone_de_magalie_battery_state:
  friendly_name: iPhone Magalie
  device_class: battery
  unit_of_measurement: '%'

sensor.iphone_de_jean_francois_battery_state:
  friendly_name: iPhone Jean
  device_class: battery
  unit_of_measurement: '%'

sensor.macbook_pro_de_jean_francois_battery_state:
  friendly_name: MacBook Jean
  device_class: battery
  unit_of_measurement: '%'

sensor.macbook_pro_de_magalie_battery_state:
  friendly_name: MacBook Magalie
  device_class: battery
  unit_of_measurement: '%'

sensor.ipad_de_magalie_battery_state:
  friendly_name: iPad Magalie
  device_class: battery
  unit_of_measurement: '%'

sensor.ipad_de_jean_francois_battery_state:
  friendly_name: iPad Jean
  device_class: battery
  unit_of_measurement: '%'

sensor.apple_watch_de_magalie_battery_state:
  friendly_name: Watch Magalie
  device_class: battery
  unit_of_measurement: '%'

sensor.apple_watch_de_jean_francois_battery_state:
  friendly_name: Watch Jean
  device_class: battery
  unit_of_measurement: '%'

