# lovelace_gen
- type: conditional
  conditions:
    - entity: input_select.floor_selector
      state: "1"
  card:
      type: custom:mod-card
      style: |
        ha-card {
          margin-left: 7px;
          margin-right: 7px;
        }
      card:
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - !include
                - '../../../base/templates/other/title-text.yaml'
                - name: Salon
              - !include
                - '../../../base/templates/other/title-text.yaml'
                - name: "[[[ return `${states['sensor.temperature'].state} °C`; ]]]"
                  justify_self: end
          - type: horizontal-stack
            cards:
              - !include
                - '../../../base/templates/button/button.yaml'
                - entity: light.lampe_sur_pied
                  label: !include ../../../base/includes/brightness-label.yaml
                  grid: light-devices-grid
                  template: '../popup-cards/light-switch.yaml'
                  lock: true
              - !include
                - '../../../base/templates/button/button.yaml'
                - entity: light.lampe_tv
                  label: !include ../../../base/includes/brightness-label.yaml
                  grid: light-devices-grid
                  template: '../popup-cards/light-switch.yaml'
                  lock: true
              - !include
                - '../../../base/templates/button/button.yaml'
                - entity: light.livingcolors
                  label: !include ../../../base/includes/brightness-label.yaml
                  grid: light-devices-grid
                  template: '../popup-cards/light-rgb.yaml'
                  lock: true
      # - type: horizontal-stack
      #   cards:
      #     - !include
      #       - '../../../base/templates/other/title-text.yaml'
      #       - name: Salle à manger
      # - type: horizontal-stack
      #   cards:
      #     - !include
      #       - '../../../base/templates/button/button.yaml'
      #       - entity: switch.shelly1_8caab5061c39
      #         label: !include ../../../base/includes/brightness-label.yaml
      #         grid: light-devices-grid
      #         template: '../popup-cards/light-switch.yaml'
      #         lock: true
      #     - !include ../../../base/includes/empty-button.yaml
      #     - !include ../../../base/includes/empty-button.yaml