# lovelace_gen
# - type: custom:mod-card
#   style: |
#     ha-card {
#       margin-left: 7px;
#       margin-right: 7px;
#     }
# - type: conditional
#   conditions:
#     - entity: input_select.floor_selector
#       state: "1"
#   card:
#     type: vertical-stack
#     cards:
#       - type: horizontal-stack
#         cards:
#           - !include
#             - '../../../base/templates/button/button.yaml'
#             - entity: light.lampe_sur_pied
#               label: !include ../../../base/includes/brightness-label.yaml
#               grid: light-devices-grid
#               template: '../popup-cards/light-rgb.yaml'
